/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DocumentDownloadButton: typeof import('./components/DocumentDownloadButton.vue')['default']
    ItemExpandedGrid: typeof import('./components/ItemExpandedGrid.vue')['default']
    ItemImage: typeof import('./components/ItemImage.vue')['default']
    ItemImageModal: typeof import('./components/ItemImageModal.vue')['default']
    ItemTechnicalProp: typeof import('./components/ItemTechnicalProp.vue')['default']
    MultiRangeSlider: typeof import('./components/MultiRangeSlider.vue')['default']
    PdfDowloadButton: typeof import('./components/PdfDowloadButton.vue')['default']
    ProductTable: typeof import('./components/ProductTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableHeader: typeof import('./components/TableHeader.vue')['default']
    TableItem: typeof import('./components/TableItem.vue')['default']
    TableItemMobile: typeof import('./components/TableItemMobile.vue')['default']
    TableItems: typeof import('./components/TableItems.vue')['default']
  }
}
